### ISSUE TITLE
Cannot read property of 'id' undefined

### ISSUE THREAD

**Issue by Zaid-maker** [DiabolusGX/djs-buttons-pagination#4]
The error occurs when try to register the command as slash command, the command works perfect with prefix message content. 

Error:
https://devmirza.is-fucking-in.space/b21e3c58-2944-4fb6-8eff-5fde4261436d

**Comment by DiabolusGX** [comment]
Not from this package, also links seems a scam xD

**Comment by Zaid-maker** [comment]
LMAO it's not a scam

**Comment by Zaid-maker** [comment]
it's a sharex upload server where my screen shots are stored

**Comment by Zaid-maker** [comment]
> Not from this package, also links seems a scam xD

Yes it's from the package the error says it all i update the markdown i accidently make it code block plus i dont use any thing in my command that uses 'id'
